Repository fernandoox/weather-app, pull requests merged in 2022-06, with the labels that each got.

#1 Chore/config api weather
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/weather-app.iml
  README.md
  src/App.tsx
  src/consts/apiConsts.ts
  src/weatherApi.ts
Labels: chore

#2 Add conection whit geocoding Api of google maps
  package-lock.json
  src/App.tsx
  src/apis/googleMapsApi.ts
  src/consts/apiConsts.ts
  src/weatherApi.ts
  yarn.lock
Labels: enhancement, chore

#5 Chore/add readme
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: documentation
